name: Run Python Script Every 5 Minutes  # Workflow name

on:
  schedule:
    - cron: '*/5 * * * *'  # This cron expression will run every 5 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest  # Runs on the latest version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the repository's code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the latest Python version available

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies from 'requirements.txt'

    - name: Run Python script
      run: |
        python code.py